### ISSUE TITLE
6 - Get drawing score (Google vision API)

### ISSUE THREAD

**Issue by radubauzh** [sopra-fs22-group-27/Pictionary-Server#6]
As a registered User who is actively playing a game, I want to know how well the drawing matches the description. 

## Acceptance criteria
- The user should see how well the drawing matches the description.

# Developement Tasks
- [x] #28

**Comment by radubauzh** [comment]
@hellasol I've updated this story after the feedback email. Is this how you meant it? If not, please change it. Thanks!

**Comment by radubauzh** [comment]
I created a new user story #80 and a new development task #81 based on the feedback we received from Roy / SoPra Team.

**Comment by sumsumcity** [comment]
This user story is the prerequisite for the user story #80

**Comment by sumsumcity** [comment]
@mrspacerobot I think this can be closed right?
